import type { AcceptanceCriterion, ActorRef, ArtifactKind, ArtifactProvider, ArtifactState, CiState, DecisionStatus, ExecutionProvider, ExecutionState, GitProvider, IntakeKind, IntakeSource, IntakeState, Priority, ReviewState, Role, SubjectRef, ViewEntity, ViewFilter, ViewLayout, WorkstreamStatus } from '../../contracts/domain.js';
import type { AgentEntity, ArtifactEntity, CommentEntity, DecisionEntity, DependencyEntity, DomainEventEntity, ExecutionEntity, InputRequestEntity, IntakeItemEntity, IntegrationConnectionEntity, MembershipEntity, RepositoryEntity, SavedViewEntity, TeamEntity, UserEntity, WorkspaceEntity, WorkstreamEntity } from '../entities/index.js';
export declare const HOUR = 3600000;
export declare const DAY: number;
type Rows<T> = Partial<T>[];
export interface SeedData {
    users: Rows<UserEntity>;
    workspace: Partial<WorkspaceEntity>;
    memberships: Rows<MembershipEntity>;
    agents: Rows<AgentEntity>;
    teams: Rows<TeamEntity>;
    repositories: Rows<RepositoryEntity>;
    workstreams: Rows<WorkstreamEntity>;
    executions: Rows<ExecutionEntity>;
    inputRequests: Rows<InputRequestEntity>;
    intake: Rows<IntakeItemEntity>;
    artifacts: Rows<ArtifactEntity>;
    decisions: Rows<DecisionEntity>;
    dependencies: Rows<DependencyEntity>;
    comments: Rows<CommentEntity>;
    events: Rows<DomainEventEntity>;
    views: Rows<SavedViewEntity>;
    integrations: Rows<IntegrationConnectionEntity>;
    counters: Record<string, number>;
}
export declare const user: (id: string) => ActorRef;
export declare const agent: (id: string) => ActorRef;
export declare const team: (id: string) => ActorRef;
export declare const SYSTEM: ActorRef;
export interface ExecOpts {
    title: string;
    description?: string;
    parent?: string;
    team?: string;
    repos?: string[];
    performers: ActorRef[];
    provider: ExecutionProvider;
    state: ExecutionState;
    deps?: string[];
    session?: string;
    branch?: string;
    note?: string;
    created: number;
    started?: number;
    done?: number;
    notes?: [number, string][];
}
export declare class SeedBuilder {
    readonly now: number;
    readonly data: SeedData;
    readonly workspaceId: string;
    private readonly keyCounters;
    constructor(now: number, workspaceId?: string);
    at: (days: number, hours?: number) => Date;
    private bump;
    event(at: Date, actor: ActorRef, type: string, subject: SubjectRef, workstreamId: string | null, data?: Record<string, unknown>): void;
    user(name: string, email: string, avatarHue: number, passwordHash: string, role: Role, created?: number): string;
    agent(name: string, provider: Exclude<ExecutionProvider, 'human'>, description: string, ownerUserId?: string): string;
    team(name: string, key: string, color: string, description: string, memberIds: string[]): string;
    repo(provider: GitProvider, fullName: string, teamIds: string[]): string;
    workstream(o: {
        key: string;
        title: string;
        objective: string;
        context?: string;
        owner: string;
        participating?: string[];
        accountable?: string;
        repos?: string[];
        criteria?: [string, AcceptanceCriterion['state']][];
        priority?: Priority;
        labels?: string[];
        path: WorkstreamStatus[];
        override?: 'draft' | 'canceled';
        target?: number;
        created: number;
        shipped?: number;
        createdBy: string;
    }): string;
    criterionEvents(workstreamId: string, key: string, items: {
        daysAgo: number;
        text: string;
        state: AcceptanceCriterion['state'];
        by: string;
    }[]): void;
    execution(workstreamId: string, o: ExecOpts): string;
    dependency(fromType: 'workstream' | 'execution', fromId: string, toType: 'workstream' | 'execution', toId: string, toWorkstreamId: string, daysAgo: number): string;
    input(workstreamId: string, o: {
        execution?: string;
        question: string;
        options?: string[];
        by: ActorRef;
        assignee?: string;
        created: number;
        answer?: {
            text: string;
            by: string;
            daysAgo: number;
        };
    }): string;
    artifact(workstreamId: string, o: {
        kind: ArtifactKind;
        provider: ArtifactProvider;
        title: string;
        execution?: string;
        repo?: string;
        url?: string;
        externalId?: string;
        state: ArtifactState;
        ci?: CiState;
        review?: ReviewState;
        conflicts?: boolean;
        env?: string;
        by: ActorRef;
        created: number;
        updated?: number;
    }): string;
    decision(o: {
        number: number;
        title: string;
        statement: string;
        rationale?: string;
        status: DecisionStatus;
        origin?: string;
        originExecution?: string;
        related?: string[];
        by: ActorRef;
        decidedBy?: string;
        created: number;
        decided?: number;
        superseded?: string;
        tags?: string[];
    }): string;
    superseded(decisionId: string, byKey: string, daysAgo: number, by: string): void;
    intake(o: {
        kind: IntakeKind;
        number: number;
        title: string;
        body?: string;
        source?: IntakeSource;
        reporterName?: string;
        reporter?: string;
        team?: string;
        priority?: Priority;
        state: IntakeState;
        workstreams?: string[];
        duplicateOf?: string;
        url?: string;
        created: number;
        triaged?: number;
        triagedBy?: string;
    }): string;
    comment(subject: SubjectRef, workstreamId: string | null, author: ActorRef, body: string, daysAgo: number): string;
    view(owner: string, name: string, entity: ViewEntity, o: {
        filters?: ViewFilter[];
        sort?: {
            field: string;
            direction: 'asc' | 'desc';
        };
        groupBy?: string;
        layout?: ViewLayout;
        shared: boolean;
        created: number;
    }): void;
}
export {};
