import {
  LucideAnchor,
  LucideApple,
  LucideArchive,
  LucideAtom,
  LucideAward,
  LucideBanknote,
  LucideBell,
  LucideBike,
  LucideBook,
  LucideBookOpen,
  LucideBookmark,
  LucideBot,
  LucideBox,
  LucideBrain,
  LucideBriefcase,
  LucideBrush,
  LucideBug,
  LucideBuilding,
  LucideCalendar,
  LucideCamera,
  LucideCar,
  LucideCastle,
  LucideChartBar,
  LucideChartLine,
  LucideChartPie,
  LucideClock,
  LucideCloud,
  LucideCode,
  LucideCoffee,
  LucideCog,
  LucideCompass,
  LucideCpu,
  LucideCreditCard,
  LucideCrown,
  LucideDatabase,
  LucideDna,
  LucideDumbbell,
  LucideEye,
  LucideFileText,
  LucideFlag,
  LucideFlame,
  LucideFlaskConical,
  LucideFlower2,
  LucideFolder,
  LucideGamepad2,
  LucideGem,
  LucideGift,
  LucideGitBranch,
  LucideGlobe,
  LucideGraduationCap,
  LucideHammer,
  LucideHandshake,
  LucideHeart,
  LucideHeartPulse,
  LucideHourglass,
  LucideImage,
  LucideInbox,
  LucideInfinity,
  LucideKey,
  LucideLandmark,
  LucideLaptop,
  LucideLayers,
  LucideLeaf,
  LucideLifeBuoy,
  LucideLightbulb,
  LucideLink,
  LucideLock,
  LucideMail,
  LucideMap,
  LucideMegaphone,
  LucideMessageSquare,
  LucideMicroscope,
  LucideMonitor,
  LucideMoon,
  LucideMountain,
  LucideMusic,
  LucideNetwork,
  LucidePackage,
  LucidePalette,
  LucidePen,
  LucidePizza,
  LucidePlane,
  LucidePuzzle,
  LucideRadio,
  LucideRocket,
  LucideSatellite,
  LucideScale,
  LucideSearch,
  LucideServer,
  LucideSettings,
  LucideShield,
  LucideShip,
  LucideShoppingCart,
  LucideSmartphone,
  LucideSnowflake,
  LucideSparkles,
  LucideStar,
  LucideStethoscope,
  LucideStore,
  LucideSun,
  LucideSwords,
  LucideTag,
  LucideTarget,
  LucideTent,
  LucideTerminal,
  LucideTrophy,
  LucideTruck,
  LucideUmbrella,
  LucideUser,
  LucideUsers,
  LucideVideo,
  LucideWallet,
  LucideWifi,
  LucideWorkflow,
  LucideWrench,
  LucideZap,
  type LucideIcon,
} from '@lucide/angular';

// Loaded on demand (dynamic import from project-glyph.ts) so the ~110 icons stay out of the initial bundle.
export interface ProjectIconEntry {
  /** Lucide kebab-case name, the value stored in `Project.icon`. */
  name: string;
  icon: LucideIcon;
}

/**
 * Curated set of lucide icons offered for projects. Only these are bundled; a stored name outside
 * this list falls back to the default glyph (emoji are always accepted).
 */
export const PROJECT_ICONS: readonly ProjectIconEntry[] = [
  { name: 'box', icon: LucideBox },
  { name: 'rocket', icon: LucideRocket },
  { name: 'flag', icon: LucideFlag },
  { name: 'target', icon: LucideTarget },
  { name: 'zap', icon: LucideZap },
  { name: 'star', icon: LucideStar },
  { name: 'heart', icon: LucideHeart },
  { name: 'flame', icon: LucideFlame },
  { name: 'lightbulb', icon: LucideLightbulb },
  { name: 'puzzle', icon: LucidePuzzle },
  { name: 'compass', icon: LucideCompass },
  { name: 'map', icon: LucideMap },
  { name: 'globe', icon: LucideGlobe },
  { name: 'cloud', icon: LucideCloud },
  { name: 'database', icon: LucideDatabase },
  { name: 'server', icon: LucideServer },
  { name: 'cpu', icon: LucideCpu },
  { name: 'code', icon: LucideCode },
  { name: 'terminal', icon: LucideTerminal },
  { name: 'bug', icon: LucideBug },
  { name: 'shield', icon: LucideShield },
  { name: 'lock', icon: LucideLock },
  { name: 'key', icon: LucideKey },
  { name: 'bell', icon: LucideBell },
  { name: 'mail', icon: LucideMail },
  { name: 'message-square', icon: LucideMessageSquare },
  { name: 'users', icon: LucideUsers },
  { name: 'user', icon: LucideUser },
  { name: 'briefcase', icon: LucideBriefcase },
  { name: 'building', icon: LucideBuilding },
  { name: 'store', icon: LucideStore },
  { name: 'shopping-cart', icon: LucideShoppingCart },
  { name: 'credit-card', icon: LucideCreditCard },
  { name: 'wallet', icon: LucideWallet },
  { name: 'banknote', icon: LucideBanknote },
  { name: 'chart-bar', icon: LucideChartBar },
  { name: 'chart-line', icon: LucideChartLine },
  { name: 'chart-pie', icon: LucideChartPie },
  { name: 'trophy', icon: LucideTrophy },
  { name: 'award', icon: LucideAward },
  { name: 'gift', icon: LucideGift },
  { name: 'palette', icon: LucidePalette },
  { name: 'brush', icon: LucideBrush },
  { name: 'pen', icon: LucidePen },
  { name: 'camera', icon: LucideCamera },
  { name: 'image', icon: LucideImage },
  { name: 'music', icon: LucideMusic },
  { name: 'video', icon: LucideVideo },
  { name: 'gamepad-2', icon: LucideGamepad2 },
  { name: 'book', icon: LucideBook },
  { name: 'book-open', icon: LucideBookOpen },
  { name: 'graduation-cap', icon: LucideGraduationCap },
  { name: 'calendar', icon: LucideCalendar },
  { name: 'clock', icon: LucideClock },
  { name: 'hourglass', icon: LucideHourglass },
  { name: 'truck', icon: LucideTruck },
  { name: 'plane', icon: LucidePlane },
  { name: 'car', icon: LucideCar },
  { name: 'ship', icon: LucideShip },
  { name: 'wrench', icon: LucideWrench },
  { name: 'hammer', icon: LucideHammer },
  { name: 'settings', icon: LucideSettings },
  { name: 'cog', icon: LucideCog },
  { name: 'package', icon: LucidePackage },
  { name: 'layers', icon: LucideLayers },
  { name: 'network', icon: LucideNetwork },
  { name: 'workflow', icon: LucideWorkflow },
  { name: 'git-branch', icon: LucideGitBranch },
  { name: 'link', icon: LucideLink },
  { name: 'search', icon: LucideSearch },
  { name: 'sparkles', icon: LucideSparkles },
  { name: 'bot', icon: LucideBot },
  { name: 'brain', icon: LucideBrain },
  { name: 'leaf', icon: LucideLeaf },
  { name: 'sun', icon: LucideSun },
  { name: 'moon', icon: LucideMoon },
  { name: 'snowflake', icon: LucideSnowflake },
  { name: 'mountain', icon: LucideMountain },
  { name: 'anchor', icon: LucideAnchor },
  { name: 'umbrella', icon: LucideUmbrella },
  { name: 'coffee', icon: LucideCoffee },
  { name: 'pizza', icon: LucidePizza },
  { name: 'apple', icon: LucideApple },
  { name: 'smartphone', icon: LucideSmartphone },
  { name: 'laptop', icon: LucideLaptop },
  { name: 'monitor', icon: LucideMonitor },
  { name: 'wifi', icon: LucideWifi },
  { name: 'radio', icon: LucideRadio },
  { name: 'satellite', icon: LucideSatellite },
  { name: 'atom', icon: LucideAtom },
  { name: 'flask-conical', icon: LucideFlaskConical },
  { name: 'microscope', icon: LucideMicroscope },
  { name: 'stethoscope', icon: LucideStethoscope },
  { name: 'dumbbell', icon: LucideDumbbell },
  { name: 'bike', icon: LucideBike },
  { name: 'tent', icon: LucideTent },
  { name: 'flower-2', icon: LucideFlower2 },
  { name: 'gem', icon: LucideGem },
  { name: 'crown', icon: LucideCrown },
  { name: 'infinity', icon: LucideInfinity },
  { name: 'life-buoy', icon: LucideLifeBuoy },
  { name: 'megaphone', icon: LucideMegaphone },
  { name: 'inbox', icon: LucideInbox },
  { name: 'file-text', icon: LucideFileText },
  { name: 'folder', icon: LucideFolder },
  { name: 'archive', icon: LucideArchive },
  { name: 'tag', icon: LucideTag },
  { name: 'bookmark', icon: LucideBookmark },
  { name: 'eye', icon: LucideEye },
  { name: 'handshake', icon: LucideHandshake },
  { name: 'heart-pulse', icon: LucideHeartPulse },
  { name: 'scale', icon: LucideScale },
  { name: 'landmark', icon: LucideLandmark },
  { name: 'swords', icon: LucideSwords },
  { name: 'castle', icon: LucideCastle },
  { name: 'dna', icon: LucideDna },
];

export const ICON_BY_NAME: ReadonlyMap<string, LucideIcon> = new Map(
  PROJECT_ICONS.map((i) => [i.name, i.icon]),
);
